import { useEffect, useState } from "react";
import { callPublicCoif, CoifHorseIntake, CoifPayload } from "./cloud/coif";

const blankHorse = (): CoifHorseIntake => ({ name: "", breed: "", age: "", color: "", use: "", currentService: "", serviceIntervalWeeks: 6, lamenessIssues: "", medicalNotes: "", temperament: "", safetyNotes: "" });
const initial: CoifPayload = { owner: { name: "", phone: "", email: "", mailingAddress: "", alternateContact: "" }, property: { name: "", serviceAddress: "", gateCode: "", parkingNotes: "", accessInstructions: "" }, horses: [blankHorse()], messagingConsent: false, signature: "" };

export default function CoifPublicPage({ token }: { token: string }) {
  const [data, setData] = useState(initial);
  const [status, setStatus] = useState<"checking" | "ready" | "submitting" | "complete" | "invalid">("checking");
  const [message, setMessage] = useState("");
  useEffect(() => {
    if (import.meta.env.DEV && token === "preview") { setStatus("ready"); return; }
    callPublicCoif(token, "inspect").then(() => setStatus("ready")).catch((error) => { setMessage(error instanceof Error ? error.message : "This link is unavailable."); setStatus("invalid"); });
  }, [token]);
  const owner = (patch: Partial<CoifPayload["owner"]>) => setData((current) => ({ ...current, owner: { ...current.owner, ...patch } }));
  const property = (patch: Partial<CoifPayload["property"]>) => setData((current) => ({ ...current, property: { ...current.property, ...patch } }));
  const horse = (index: number, patch: Partial<CoifHorseIntake>) => setData((current) => ({ ...current, horses: current.horses.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) }));
  if (status === "checking") return <main className="coif-public-shell"><section className="coif-public-card"><p className="eyebrow">FarrierOS secure intake</p><h1>Checking your link…</h1></section></main>;
  if (status === "invalid") return <main className="coif-public-shell"><section className="coif-public-card"><p className="eyebrow">Link unavailable</p><h1>This COIF cannot be opened</h1><p>{message}</p></section></main>;
  if (status === "complete") return <main className="coif-public-shell"><section className="coif-public-card coif-success"><div className="coif-success-mark">✓</div><p className="eyebrow">Submission received</p><h1>Thank you</h1><p>Your information was securely sent to your farrier for review. You may close this page.</p></section></main>;
  return <main className="coif-public-shell"><form className="coif-public-form" onSubmit={async (event) => { event.preventDefault(); setStatus("submitting"); try { await callPublicCoif(token, "submit", data); setStatus("complete"); } catch (error) { setMessage(error instanceof Error ? error.message : "Submission failed."); setStatus("ready"); } }}>
    <header className="coif-hero"><div className="brand-mark">F</div><p className="eyebrow">Client Onboarding Information Form</p><h1>Welcome to FarrierOS</h1><p>Share your contact, property, and horse information directly with your farrier. Add every horse they may service.</p></header>
    {message && <div className="billing-notice">{message}</div>}
    <section className="coif-public-card"><span className="coif-step">01</span><h2>Owner information</h2><div className="form-grid"><label>Full name<input required value={data.owner.name} onChange={(e) => owner({ name: e.target.value })} /></label><label>Mobile phone<input required type="tel" value={data.owner.phone} onChange={(e) => owner({ phone: e.target.value })} /></label><label>Email<input type="email" value={data.owner.email} onChange={(e) => owner({ email: e.target.value })} /></label><label>Mailing address<input value={data.owner.mailingAddress} onChange={(e) => owner({ mailingAddress: e.target.value })} /></label><label className="editor-wide">Alternate contact<input placeholder="Name and phone" value={data.owner.alternateContact} onChange={(e) => owner({ alternateContact: e.target.value })} /></label></div></section>
    <section className="coif-public-card"><span className="coif-step">02</span><h2>Barn or service property</h2><div className="form-grid"><label>Property or barn name<input value={data.property.name} onChange={(e) => property({ name: e.target.value })} /></label><label>Service address<input required value={data.property.serviceAddress} onChange={(e) => property({ serviceAddress: e.target.value })} /></label><label>Gate code<input value={data.property.gateCode} onChange={(e) => property({ gateCode: e.target.value })} /></label><label>Parking notes<input value={data.property.parkingNotes} onChange={(e) => property({ parkingNotes: e.target.value })} /></label><label className="editor-wide">Access instructions<textarea value={data.property.accessInstructions} onChange={(e) => property({ accessInstructions: e.target.value })} /></label></div></section>
    <section className="coif-public-card"><span className="coif-step">03</span><div className="section-heading"><div><h2>Horse information</h2><p>Add each horse your farrier may service.</p></div><button type="button" onClick={() => setData((current) => ({ ...current, horses: [...current.horses, blankHorse()] }))}>+ Add Another Horse</button></div><div className="coif-horse-list">{data.horses.map((item, index) => <article className="coif-horse-card" key={index}><div className="section-heading"><h3>Horse {index + 1}</h3>{data.horses.length > 1 && <button className="danger-button" type="button" onClick={() => setData((current) => ({ ...current, horses: current.horses.filter((_, i) => i !== index) }))}>Remove</button>}</div><div className="form-grid"><label>Name<input required value={item.name} onChange={(e) => horse(index, { name: e.target.value })} /></label><label>Breed<input value={item.breed} onChange={(e) => horse(index, { breed: e.target.value })} /></label><label>Age<input value={item.age} onChange={(e) => horse(index, { age: e.target.value })} /></label><label>Color<input value={item.color} onChange={(e) => horse(index, { color: e.target.value })} /></label><label>Primary use<input placeholder="Trail, performance, ranch…" value={item.use} onChange={(e) => horse(index, { use: e.target.value })} /></label><label>Current farrier service<input placeholder="Trim, fronts, full set…" value={item.currentService} onChange={(e) => horse(index, { currentService: e.target.value })} /></label><label>Service interval (weeks)<input max="16" min="1" type="number" value={item.serviceIntervalWeeks} onChange={(e) => horse(index, { serviceIntervalWeeks: Number(e.target.value) || 6 })} /></label><label>Temperament<input value={item.temperament} onChange={(e) => horse(index, { temperament: e.target.value })} /></label><label className="editor-wide">Lameness or injury concerns<textarea value={item.lamenessIssues} onChange={(e) => horse(index, { lamenessIssues: e.target.value })} /></label><label className="editor-wide">Medical notes relevant to hoof care<textarea value={item.medicalNotes} onChange={(e) => horse(index, { medicalNotes: e.target.value })} /></label><label className="editor-wide">Handling and safety notes<textarea value={item.safetyNotes} onChange={(e) => horse(index, { safetyNotes: e.target.value })} /></label></div></article>)}</div></section>
    <section className="coif-public-card"><span className="coif-step">04</span><h2>Review and consent</h2><label className="toggle-row"><input checked={data.messagingConsent} type="checkbox" onChange={(e) => setData((current) => ({ ...current, messagingConsent: e.target.checked }))} /><span>I agree to receive appointment-related text messages from my farrier.</span></label><label>Electronic signature<input required placeholder="Type your full legal name" value={data.signature} onChange={(e) => setData((current) => ({ ...current, signature: e.target.value }))} /></label><p className="helper-text">By submitting, you confirm this information is accurate to the best of your knowledge. Your farrier will review it before adding it to their records.</p><button className="primary save-button" disabled={status === "submitting"} type="submit">{status === "submitting" ? "Sending securely…" : "Submit to My Farrier"}</button></section>
  </form></main>;
}
