import { AppData } from "./types";
import { shiftDate, TODAY, TOMORROW } from "./dateUtils";
import { fullAccessPlan } from "./membership";

export { TODAY, TOMORROW };

export const sampleData: AppData = {
  business: {
    id: "biz-1",
    businessName: "FarrierOS Demo Forge",
    farrierName: "Demo Farrier",
    phone: "(555) 018-2244",
    email: "demo@farrieros.local",
    baseLocation: "Fort Collins, CO",
    defaultServiceIntervalWeeks: 6,
  },
  membership: fullAccessPlan,
  collaborationMembers: [
    {
      id: "member-owner",
      name: "Demo Farrier",
      role: "owner",
      notificationsEnabled: true,
    },
    {
      id: "member-partner",
      name: "Casey Bell",
      role: "business_partner",
      notificationsEnabled: true,
    },
    {
      id: "member-apprentice",
      name: "Jordan Hale",
      role: "apprentice",
      notificationsEnabled: true,
    },
  ],
  activityPings: [
    {
      id: "ping-seed-1",
      actorName: "Casey Bell",
      message: "Fluffy was moved to the first stop tomorrow at Willow Creek Ranch.",
      createdAt: "2026-07-06T07:45:00",
      read: false,
    },
    {
      id: "ping-seed-2",
      actorName: "Jordan Hale",
      message: "Prep note added: shape RF with fuller lateral branch.",
      createdAt: "2026-07-06T08:10:00",
      read: false,
    },
  ],
  clients: [
    {
      id: "client-sarah",
      name: "Sarah Morgan",
      phone: "(555) 014-7788",
      email: "sarah.morgan@example.local",
      notes: "Prefers morning appointments. Fluffy is handled by barn staff when Sarah is traveling.",
      horseIds: ["horse-fluffy"],
      barnIds: ["barn-willow"],
    },
  ],
  barns: [
    {
      id: "barn-willow",
      name: "Willow Creek Ranch",
      clientIds: ["client-sarah"],
      address: "1248 Willow Creek Road, Fort Collins, CO",
      latitude: 40.5853,
      longitude: -105.0844,
      gateCode: "2468#",
      parkingNotes: "Park by the south equipment shed. Leave room for hay delivery.",
      barnManagerName: "Mia Torres",
      barnManagerPhone: "(555) 019-4421",
      accessInstructions: "Use the west gate. Cross-tie space is in aisle 2. Power outlet near tack room.",
      horseIds: ["horse-fluffy"],
    },
  ],
  horses: [
    {
      id: "horse-fluffy",
      name: "Fluffy",
      ownerClientId: "client-sarah",
      barnPropertyId: "barn-willow",
      temperament: "Good to handle, impatient on RF after 15 minutes.",
      safetyNotes: "Use low stand on fronts. Keep hay net nearby. Do not crowd right shoulder.",
      serviceIntervalWeeks: 6,
      lastServiceDate: shiftDate(TODAY, -42),
      nextDueDate: TOMORROW,
      footRecordIds: {
        LF: "foot-fluffy-lf",
        RF: "foot-fluffy-rf",
        LH: "foot-fluffy-lh",
        RH: "foot-fluffy-rh",
      },
      verifiedSetupId: "service-2026-05-26",
      notes: [
        "Tracks best with a slightly wider web up front.",
        "Owner wants concise summaries only when something changed.",
        "Check medial heel growth each cycle.",
      ],
      photoDocumentIds: ["photo-rf-trim", "photo-rf-finish", "photo-lf-trim", "photo-xray-placeholder"],
    },
  ],
  footRecords: [
    {
      id: "foot-fluffy-lf",
      horseId: "horse-fluffy",
      foot: "LF",
      currentSetupId: "setup-lf-2026-05-26",
      historySetupIds: ["setup-lf-2026-05-26"],
      trimmedPhotoIds: ["photo-lf-trim"],
      finishedShoePhotoIds: ["photo-lf-finish"],
      notes: ["Slight flare lateral quarter. Keep toe backed up."],
    },
    {
      id: "foot-fluffy-rf",
      horseId: "horse-fluffy",
      foot: "RF",
      currentSetupId: "setup-rf-2026-05-26",
      historySetupIds: ["setup-rf-2026-05-26"],
      trimmedPhotoIds: ["photo-rf-trim"],
      finishedShoePhotoIds: ["photo-rf-finish"],
      notes: ["Medial heel runs forward. Fuller lateral branch. Watch nail line in quarter."],
    },
    {
      id: "foot-fluffy-lh",
      horseId: "horse-fluffy",
      foot: "LH",
      currentSetupId: "setup-lh-2026-05-26",
      historySetupIds: ["setup-lh-2026-05-26"],
      trimmedPhotoIds: ["photo-lh-trim"],
      finishedShoePhotoIds: ["photo-lh-finish"],
      notes: ["Plain stamped hind. Toe wants to run long late cycle."],
    },
    {
      id: "foot-fluffy-rh",
      horseId: "horse-fluffy",
      foot: "RH",
      currentSetupId: "setup-rh-2026-05-26",
      historySetupIds: ["setup-rh-2026-05-26"],
      trimmedPhotoIds: ["photo-rh-trim"],
      finishedShoePhotoIds: ["photo-rh-finish"],
      notes: ["Slight medial quarter crack grown out. Keep finish conservative."],
    },
  ],
  shoeSetups: [
    {
      id: "setup-lf-2026-05-26",
      horseId: "horse-fluffy",
      foot: "LF",
      serviceRecordId: "service-2026-05-26",
      shoeBrand: "Kerckhaert",
      shoeModel: "SX-8 Front",
      shoeSize: "1",
      clips: "Toe clip",
      pads: "None",
      wedges: "None",
      borium: "None",
      modifications: "Rolled toe, boxed lateral heel",
      fitNotes: "Fit full through quarters; leave a hair extra lateral heel support.",
      verified: true,
      verifiedAt: "2026-05-26T15:20:00",
      changedThisCycle: "Backed toe up 3 mm from April setup.",
    },
    {
      id: "setup-rf-2026-05-26",
      horseId: "horse-fluffy",
      foot: "RF",
      serviceRecordId: "service-2026-05-26",
      shoeBrand: "Kerckhaert",
      shoeModel: "SX-8 Front",
      shoeSize: "1",
      clips: "Toe clip",
      pads: "Leather rim pad",
      wedges: "None",
      borium: "Small heel dots",
      modifications: "Fuller lateral branch; ease medial heel",
      fitNotes: "Medial heel runs forward. Keep shoe seated and avoid crowding right shoulder.",
      verified: true,
      verifiedAt: "2026-05-26T15:20:00",
      changedThisCycle: "Added rim pad after soreness on hard ground.",
    },
    {
      id: "setup-lh-2026-05-26",
      horseId: "horse-fluffy",
      foot: "LH",
      serviceRecordId: "service-2026-05-26",
      shoeBrand: "Kerckhaert",
      shoeModel: "DF Select Hind",
      shoeSize: "0",
      clips: "Quarter clips",
      pads: "None",
      wedges: "None",
      borium: "None",
      modifications: "Set toe back; slight trailer removed",
      fitNotes: "Keep toe short. Good heel purchase.",
      verified: true,
      verifiedAt: "2026-05-26T15:20:00",
      changedThisCycle: "No meaningful change.",
    },
    {
      id: "setup-rh-2026-05-26",
      horseId: "horse-fluffy",
      foot: "RH",
      serviceRecordId: "service-2026-05-26",
      shoeBrand: "Kerckhaert",
      shoeModel: "DF Select Hind",
      shoeSize: "0",
      clips: "Quarter clips",
      pads: "None",
      wedges: "None",
      borium: "None",
      modifications: "Box medial branch, clean quarter crack edge",
      fitNotes: "Conservative finish near old crack. Do not rasp wall thin.",
      verified: true,
      verifiedAt: "2026-05-26T15:20:00",
      changedThisCycle: "Quarter crack nearly grown out.",
    },
  ],
  serviceRecords: [
    {
      id: "service-2026-05-26",
      horseId: "horse-fluffy",
      appointmentId: "appt-2026-05-26",
      serviceDate: "2026-05-26",
      serviceType: "full_set",
      footSetupIds: ["setup-lf-2026-05-26", "setup-rf-2026-05-26", "setup-lh-2026-05-26", "setup-rh-2026-05-26"],
      writtenNotes: "Full set. Fluffy stood well. RF medial heel still wants to run forward.",
      voiceNotePlaceholderIds: ["voice-2026-05-26"],
      photoDocumentIds: ["photo-rf-trim", "photo-rf-finish", "photo-lf-trim"],
      verifiedSetup: true,
      nextDueDate: "2026-07-07",
      ownerSummaryPreview: "Fluffy received a full set. RF rim pad kept in place; next visit due July 7.",
      createdAt: "2026-05-26T15:20:00",
      updatedAt: "2026-05-26T15:20:00",
    },
  ],
  appointments: [
    {
      id: "appt-today-fluffy",
      date: TODAY,
      startTime: "09:00",
      endTime: "10:15",
      barnPropertyId: "barn-willow",
      clientId: "client-sarah",
      horseIds: ["horse-fluffy"],
      status: "scheduled",
      routeOrder: 1,
      notes: "Bring rim pad stock and size 1 fronts.",
      recurringIntervalWeeks: 6,
      shoesPrepped: false,
      prepNote: "",
    },
    {
      id: "appt-tomorrow-fluffy",
      date: TOMORROW,
      startTime: "08:30",
      endTime: "09:45",
      barnPropertyId: "barn-willow",
      clientId: "client-sarah",
      horseIds: ["horse-fluffy"],
      status: "scheduled",
      routeOrder: 1,
      notes: "Pre-shape fronts tonight. Check RF pad decision before nailing.",
      recurringIntervalWeeks: 6,
      shoesPrepped: false,
      prepNote: "Shape RF with fuller lateral branch.",
    },
    {
      id: "appt-week-fluffy-1",
      date: shiftDate(TODAY, 2),
      startTime: "10:30",
      endTime: "11:30",
      barnPropertyId: "barn-willow",
      clientId: "client-sarah",
      horseIds: ["horse-fluffy"],
      status: "scheduled",
      routeOrder: 2,
      notes: "Demo follow-up block for week view.",
      recurringIntervalWeeks: 6,
      shoesPrepped: false,
      prepNote: "Bring spare size 1 fronts.",
    },
    {
      id: "appt-week-fluffy-2",
      date: shiftDate(TODAY, 4),
      startTime: "13:00",
      endTime: "14:00",
      barnPropertyId: "barn-willow",
      clientId: "client-sarah",
      horseIds: ["horse-fluffy"],
      status: "scheduled",
      routeOrder: 1,
      notes: "Demo reschedule target for team ping.",
      recurringIntervalWeeks: 6,
      shoesPrepped: false,
      prepNote: "",
    },
    {
      id: "appt-month-fluffy",
      date: shiftDate(TODAY, 16),
      startTime: "09:30",
      endTime: "10:30",
      barnPropertyId: "barn-willow",
      clientId: "client-sarah",
      horseIds: ["horse-fluffy"],
      status: "scheduled",
      routeOrder: 1,
      notes: "Month-view demo appointment.",
      recurringIntervalWeeks: 6,
      shoesPrepped: false,
      prepNote: "",
    },
  ],
  photos: [
    {
      id: "photo-rf-trim",
      horseId: "horse-fluffy",
      foot: "RF",
      serviceRecordId: "service-2026-05-26",
      type: "trimmed_foot",
      title: "RF trimmed foot - May 26",
      placeholderColor: "#6b7a63",
      capturedAt: "2026-05-26T14:58:00",
      notes: "Medial heel running forward before shoe fit.",
    },
    {
      id: "photo-rf-finish",
      horseId: "horse-fluffy",
      foot: "RF",
      serviceRecordId: "service-2026-05-26",
      type: "finished_shoe",
      title: "RF finished shoe - May 26",
      placeholderColor: "#8b6f47",
      capturedAt: "2026-05-26T15:14:00",
      notes: "Rim pad and small heel dots visible.",
    },
    {
      id: "photo-lf-trim",
      horseId: "horse-fluffy",
      foot: "LF",
      serviceRecordId: "service-2026-05-26",
      type: "trimmed_foot",
      title: "LF trimmed foot - May 26",
      placeholderColor: "#5f767e",
      capturedAt: "2026-05-26T14:34:00",
      notes: "Toe backed up before fit.",
    },
    {
      id: "photo-lf-finish",
      horseId: "horse-fluffy",
      foot: "LF",
      serviceRecordId: "service-2026-05-26",
      type: "finished_shoe",
      title: "LF finished shoe - May 26",
      placeholderColor: "#766b5d",
      capturedAt: "2026-05-26T14:46:00",
      notes: "Toe clip seated cleanly.",
    },
    {
      id: "photo-lh-trim",
      horseId: "horse-fluffy",
      foot: "LH",
      serviceRecordId: "service-2026-05-26",
      type: "trimmed_foot",
      title: "LH trimmed foot - May 26",
      placeholderColor: "#746d86",
      capturedAt: "2026-05-26T14:12:00",
      notes: "Toe before shoe fit.",
    },
    {
      id: "photo-lh-finish",
      horseId: "horse-fluffy",
      foot: "LH",
      serviceRecordId: "service-2026-05-26",
      type: "finished_shoe",
      title: "LH finished shoe - May 26",
      placeholderColor: "#7f694f",
      capturedAt: "2026-05-26T14:25:00",
      notes: "Plain clean hind finish.",
    },
    {
      id: "photo-rh-trim",
      horseId: "horse-fluffy",
      foot: "RH",
      serviceRecordId: "service-2026-05-26",
      type: "trimmed_foot",
      title: "RH trimmed foot - May 26",
      placeholderColor: "#6d7b7a",
      capturedAt: "2026-05-26T13:49:00",
      notes: "Quarter crack edge clean.",
    },
    {
      id: "photo-rh-finish",
      horseId: "horse-fluffy",
      foot: "RH",
      serviceRecordId: "service-2026-05-26",
      type: "finished_shoe",
      title: "RH finished shoe - May 26",
      placeholderColor: "#85735d",
      capturedAt: "2026-05-26T14:02:00",
      notes: "Conservative finish around old crack.",
    },
    {
      id: "photo-xray-placeholder",
      horseId: "horse-fluffy",
      type: "xray",
      title: "RF lateral X-ray placeholder",
      placeholderColor: "#41505f",
      capturedAt: "2026-05-12T10:30:00",
      notes: "Placeholder only. No real imaging stored in Prototype 0.",
    },
  ],
  preferences: { theme: "system", currency: "USD" },
  expenses: [],
};
